name: dynamic
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - flask
  - opencv-python
  - numpy
  - scipy
  - pip
  - pip:
    - onnxruntime
    - watchdog
    - mediapipe
    - flask-cors
    - flask-socketio
    - eventlet
    - python-dotenv
    - pillow
    - requests
