// 手势识别相关常量管理

const MAX_HISTORY_LENGTH = Number(import.meta.env.VITE_MAX_HISTORY_LENGTH) || 30
const STABILITY_THRESHOLD = Number(import.meta.env.VITE_STABILITY_THRESHOLD) || 0.5
const MIN_HISTORY_LENGTH_STATIC = Number(import.meta.env.VITE_MIN_HISTORY_LENGTH_STATIC) || 3
const MIN_HISTORY_LENGTH_DYNAMIC = Number(import.meta.env.VITE_MIN_HISTORY_LENGTH_DYNAMIC) || 5
const STABILITY_THRESHOLD_STATIC = Number(import.meta.env.VITE_STABILITY_THRESHOLD_STATIC) || 0.5
const STABILITY_THRESHOLD_DYNAMIC = Number(import.meta.env.VITE_STABILITY_THRESHOLD_DYNAMIC) || 0.45

const ACTION_COOLDOWN = Number(import.meta.env.VITE_ACTION_COOLDOWN) || 300
const AUTO_STOP_DELAY = Number(import.meta.env.VITE_AUTO_STOP_DELAY) || 2000

const CONNECTION_TIMEOUT = Number(import.meta.env.VITE_CONNECTION_TIMEOUT) || 3000
const MAX_RETRIES = Number(import.meta.env.VITE_MAX_RETRIES) || 1
const MIN_REQUEST_INTERVAL = Number(import.meta.env.VITE_MIN_REQUEST_INTERVAL) || 33
const IMAGE_WIDTH = Number(import.meta.env.VITE_IMAGE_WIDTH) || 320
const IMAGE_HEIGHT = Number(import.meta.env.VITE_IMAGE_HEIGHT) || 240
const IMAGE_QUALITY = Number(import.meta.env.VITE_IMAGE_QUALITY) || 0.7

const ZOOM_STEP = Number(import.meta.env.VITE_ZOOM_STEP) || 0.2
const MIN_CAMERA_DISTANCE = Number(import.meta.env.VITE_MIN_CAMERA_DISTANCE) || 0.1
const MAX_CAMERA_DISTANCE = Number(import.meta.env.VITE_MAX_CAMERA_DISTANCE) || 1
const ROTATION_SENSITIVITY = Number(import.meta.env.VITE_ROTATION_SENSITIVITY) || 0.5

export const ACTION_RECOGNITION_CONFIG = {
  MAX_HISTORY_LENGTH,
  STABILITY_THRESHOLD,
  MIN_HISTORY_LENGTH_STATIC,
  MIN_HISTORY_LENGTH_DYNAMIC,
  STABILITY_THRESHOLD_STATIC,
  STABILITY_THRESHOLD_DYNAMIC
}

export const GESTURE_CONTROL_CONFIG = {
  ACTION_COOLDOWN,
  AUTO_STOP_DELAY,
  ZOOM_ACTION_RESET_TIME: 1000,
  DEFAULT_ACTION_RESET_TIME: 3000
}

export const BACKEND_CONFIG = {
  CONNECTION_TIMEOUT,
  MAX_RETRIES,
  MIN_REQUEST_INTERVAL,
  IMAGE_WIDTH,
  IMAGE_HEIGHT,
  IMAGE_QUALITY
}

export const MODEL_CONTROL_CONFIG = {
  ZOOM_STEP,
  MIN_CAMERA_DISTANCE,
  MAX_CAMERA_DISTANCE,
  DEFAULT_CAMERA_ORBIT: '0deg 75deg 0.5m',
  ROTATION_SENSITIVITY
}

export const GESTURE_MAPPINGS = {
  ZOOM_IN: [27, 39],
  ZOOM_OUT: [24],
  ROTATE: [19, 30, 31, 35, 36, 29],
  DYNAMIC_GESTURES: [19, 30],
  STATIC_GESTURES: [27, 39, 24]
}

export type ActionType = 'zoom_in' | 'zoom_out' | 'rotate' | 'switch' | 'switch_next' | 'switch_prev' | 'reset' | 'toggle_thumbbar'
